name: PR Chat
on:
  pull_request_target:
    types: [opened, ready_for_review, closed]

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: stable
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Code Review Chat
        uses: ./actions/code-review-chat
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_bot_name: 'VSCodeBot'
          notification_channel: codereview
